version: '3'

vars:
  SSH_USER: ubuntu
  INVENTORY_FILE: inventory/petra_cluster/inventory.ini
  KUBESPRAY_DIR: kubespray
  
  PROJECT_ROOT:
    sh: pwd
  ANSIBLE_BIN: "{{.PROJECT_ROOT}}/.venv/bin/ansible-playbook"
  INVENTORY_ABS: "{{.PROJECT_ROOT}}/{{.INVENTORY_FILE}}"

env:
  ANSIBLE_HOST_KEY_CHECKING: "False"
  ANSIBLE_PYTHON_INTERPRETER: auto_silent

tasks:
  default:
    desc: Shows the list of available tasks
    cmds:
      - task --list

  init:
    desc: "Initializes the environment: Submodule, Python venv and dependencies"
    cmds:
      - echo "Updating the Kubespray submodule..."
      - git submodule update --init --recursive
      - echo "Creating the Python venv..."
      - python3 -m venv .venv
      - echo "Installing dependencies..."
      - ".venv/bin/pip install -U pip"
      - ".venv/bin/pip install -r {{.KUBESPRAY_DIR}}/requirements.txt"
      - echo "Ready to go!"

  ping:
    desc: "Checks the SSH connection with all nodes"
    cmds:
      - ".venv/bin/ansible -i {{.INVENTORY_FILE}} all -m ping --user {{.SSH_USER}} --become"

  deploy:
    desc: "Deploys the complete cluster (cluster.yml)"
    summary: |
      Deploys the main playbook.
      Usage: task deploy
    dir: "{{.KUBESPRAY_DIR}}"
    cmds:
      - >
        {{.ANSIBLE_BIN}}
        -i {{.INVENTORY_ABS}}
        --user={{.SSH_USER}}
        --become
        --become-user=root
        cluster.yml

  reset:
    desc: "DANGER : Delete Kubernetes and reset nodes (reset.yml)"
    prompt: "Are you sure you want to delete the cluster ?"
    dir: "{{.KUBESPRAY_DIR}}"
    cmds:
      - >
        {{.ANSIBLE_BIN}}
        -i {{.INVENTORY_ABS}}
        --user={{.SSH_USER}}
        --become
        --become-user=root
        reset.yml

  upgrade-kubernetes-version:
    desc: "DANGER : Upgrade kubernetes version (upgrade-cluster.yml)"
    prompt: "Upgrading cluster is untested. Are you sure you want to upgrade the cluster ?"
    dir: "{{.KUBESPRAY_DIR}}"
    cmds:
      - >
        {{.ANSIBLE_BIN}}
        -i {{.INVENTORY_ABS}}
        --user={{.SSH_USER}}
        --become
        --become-user=root
        upgrade-cluster.yml

  remove-node:
    desc: "Remove a specific node from the cluster"
    vars:
      NODE: '{{default "" .NODE}}'
    preconditions:
      - sh: '[ -n "{{.NODE}}" ]'
        msg: "You must specify a node! Example: task remove-node NODE=node1"
    dir: "{{.KUBESPRAY_DIR}}"
    cmds:
      - >
        {{.ANSIBLE_BIN}}
        -i {{.INVENTORY_ABS}}
        --user={{.SSH_USER}}
        --become
        --become-user=root
        -e node={{.NODE}}
        -e reset_nodes=true
        remove-node.yml

  reconfigure-node:
    desc: "Apply the configuration on a SINGLE node (cluster.yml --limit)"
    vars:
      NODE: '{{default "" .NODE}}'
    preconditions:
      - sh: '[ -n "{{.NODE}}" ]'
        msg: "You must specify a node! Example: task reconfigure-node NODE=node1"
    dir: "{{.KUBESPRAY_DIR}}"
    cmds:
      - echo "Reconfiguring node {{.NODE}} only..."
      - >
        {{.ANSIBLE_BIN}}
        -i {{.INVENTORY_ABS}}
        --user={{.SSH_USER}}
        --become
        --become-user=root
        --limit={{.NODE}}
        cluster.yml

  get-kubeconfig:
    desc: "Retrieve the admin.conf file from the first master"
    vars:
      MASTER_IP: '{{default "" .IP}}'
    preconditions:
      - sh: '[ -n "{{.MASTER_IP}}" ]'
        msg: "You must specify the master IP! Example: task get-kubeconfig IP=192.168.1.10"
    cmds:
      - echo "Retrieving the config file..."
      - ssh -o StrictHostKeyChecking=no {{.SSH_USER}}@{{.MASTER_IP}} "sudo cp /etc/kubernetes/admin.conf /tmp/admin.conf && sudo chown {{.SSH_USER}} /tmp/admin.conf"
      - scp -o StrictHostKeyChecking=no {{.SSH_USER}}@{{.MASTER_IP}}:/tmp/admin.conf ~/.kube/config
      - ssh -o StrictHostKeyChecking=no {{.SSH_USER}}@{{.MASTER_IP}} "rm /tmp/admin.conf"
      - echo "Correcting permissions..."
      - chmod 600 ~/.kube/config
      - echo "Replacing localhost/127.0.0.1 by the master IP..."
      - sed -i 's/127.0.0.1/{{.MASTER_IP}}/g' ~/.kube/config
      - echo "Kubeconfig installed !"